# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."bookstack" = {
    image = "lscr.io/linuxserver/bookstack:latest";
    volumes = [
      "/config/bookstack/config:/config:rw"
    ];
    ports = [
      "127.0.0.1:8120:80/tcp"
    ];
    dependsOn = [
      "bookstack-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bookstack"
      "--network=bookstack_default"
    ];
    environmentFiles = [
      /config/env/bookstack.env
    ];
  };
  systemd.services."podman-bookstack" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-bookstack_default.service"
    ];
    requires = [
      "podman-network-bookstack_default.service"
    ];
    partOf = [
      "podman-compose-bookstack-root.target"
    ];
    wantedBy = [
      "podman-compose-bookstack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."bookstack-db" = {
    image = "docker.io/mariadb:latest";
    volumes = [
      "/config/bookstack/db:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bookstack-db"
      "--network=bookstack_default"
    ];
    environmentFiles = [
      /config/env/bookstack.env
    ];
  };
  systemd.services."podman-bookstack-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-bookstack_default.service"
    ];
    requires = [
      "podman-network-bookstack_default.service"
    ];
    partOf = [
      "podman-compose-bookstack-root.target"
    ];
    wantedBy = [
      "podman-compose-bookstack-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-bookstack_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f bookstack_default";
    };
    script = ''
      podman network inspect bookstack_default || podman network create bookstack_default
    '';
    partOf = [ "podman-compose-bookstack-root.target" ];
    wantedBy = [ "podman-compose-bookstack-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-bookstack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
