# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."wordpress-db" = {
    image = "mysql:8.0";
    environmentFiles = [ "/config/env/wordpress.env" ];
    volumes = [
      "/nest0/wordpress/db:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=wordpress_default"
    ];
  };
  systemd.services."podman-wordpress-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wordpress_default.service"
    ];
    requires = [
      "podman-network-wordpress_default.service"
    ];
    partOf = [
      "podman-compose-wordpress-root.target"
    ];
    wantedBy = [
      "podman-compose-wordpress-root.target"
    ];
  };
  virtualisation.oci-containers.containers."wordpress-wordpress" = {
    image = "docker.io/wordpress";
    environmentFiles = [ "/config/env/wordpress.env" ];
    volumes = [
      "/nest0/wordpress/config:/var/www/html:rw"
    ];
    ports = [
      "127.0.0.1:29138:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wordpress"
      "--network=wordpress_default"
    ];
  };
  systemd.services."podman-wordpress-wordpress" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wordpress_default.service"
    ];
    requires = [
      "podman-network-wordpress_default.service"
    ];
    partOf = [
      "podman-compose-wordpress-root.target"
    ];
    wantedBy = [
      "podman-compose-wordpress-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-wordpress_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f wordpress_default";
    };
    script = ''
      podman network inspect wordpress_default || podman network create wordpress_default
    '';
    partOf = [ "podman-compose-wordpress-root.target" ];
    wantedBy = [ "podman-compose-wordpress-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-wordpress-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
