name: "Flake update"
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Update flake"
        run: nix flake update
      - name: "Check flake"
        run: nix flake check --all-systems
      - name: "Commit changes"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -a -m "Update flake"
          git push
